In [1]:
import pandas as pd 
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
s=pd.Series([100,200,300],
            index=['A','B','C'])
print(s)

A    100
B    200
C    300
dtype: int64

In [5]:
data={
    'maths':90,
    'physics':80,
     'chemistry':88
}
s=pd.Series(data)
print(s)

maths        90
physics      80
chemistry    88
dtype: int64

In [6]:
s=pd.Series([10,20,30,40])
print(s[0])

10

In [7]:
s=pd.Series([100,200,300],
            index=['A','B','C'])
print(s['B'])

200

In [8]:
print(s[['A','C']])

A    100
C    300
dtype: int64

In [9]:
print(s.size)

3

In [10]:
print(s.shape)

(3,)

In [11]:
print(s.dtype)

int64

In [13]:
s=pd.Series([10,20,30,40])
print(s+10)

0    20
1    30
2    40
3    50
dtype: int64

In [14]:
print(s*2)

0    20
1    40
2    60
3    80
dtype: int64

In [15]:
print("sum=",s.sum())
print("mean=",s.mean())
print("maximum=",s.max())
print("minimum=",s.min())

sum= 100
mean= 25.0
maximum= 40
minimum= 10

In [19]:
data={
    'Rollno':[101,102,103],
    'Name':['Arun','Priya','Rahul'],
    'Marks':[85,90,78]
}
df=pd.DataFrame(data)
print(df)

   Rollno   Name  Marks
0     101   Arun     85
1     102  Priya     90
2     103  Rahul     78

In [15]:
import pandas as pd
data={
    'Rollno':[101,102,103],
    'Name':['Arun','Priya','Rahul'],
    'Marks':[85,90,78]
}
df=pd.DataFrame(data,
                index=['A','B','C'])
print(df)
print(df.index)
print(df.dtypes)
print(df.columns)

   Rollno   Name  Marks
A     101   Arun     85
B     102  Priya     90
C     103  Rahul     78
Index(['A', 'B', 'C'], dtype='object')
Rollno     int64
Name      object
Marks      int64
dtype: object
Index(['Rollno', 'Name', 'Marks'], dtype='object')

In [16]:
print(df[['Name','Marks']])

    Name  Marks
A   Arun     85
B  Priya     90
C  Rahul     78

In [20]:
print(df['Name'])

A     Arun
B    Priya
C    Rahul
Name: Name, dtype: object

In [24]:
print(df.loc['A'])

Rollno     101
Name      Arun
Marks       85
Name: A, dtype: object

In [25]:
print(df.loc[['A','C']])

   Rollno   Name  Marks
A     101   Arun     85
C     103  Rahul     78

In [26]:
print(df.iloc[1])

Rollno      102
Name      Priya
Marks        90
Name: B, dtype: object

In [27]:
print(df.iloc[[0,2]])

   Rollno   Name  Marks
A     101   Arun     85
C     103  Rahul     78

In [28]:
print(df.iloc[0:2,1:3])

    Name  Marks
A   Arun     85
B  Priya     90

In [30]:
df['Grade']=['A','A+','B']
print(df)

   Rollno   Name  Marks Grade
A     101   Arun     85     A
B     102  Priya     90    A+
C     103  Rahul     78     B

In [31]:
df['Marks']=df['Marks']+5
print(df)

   Rollno   Name  Marks Grade
A     101   Arun     90     A
B     102  Priya     95    A+
C     103  Rahul     83     B

In [35]:
df.drop('Grade',
        axis=1,
        inplace=True)

KeyError: "['Grade'] not found in axis"

In [36]:
print(df)

   Rollno   Name  Marks
A     101   Arun     90
B     102  Priya     95
C     103  Rahul     83

In [37]:
print(df['Marks'].sum())

268

In [38]:
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].min())

89.33333333333333
95
83

In [39]:
df.sort_values('Marks')

   Rollno   Name  Marks
C     103  Rahul     83
A     101   Arun     90
B     102  Priya     95

In [41]:
df.sort_values('Marks',
               ascending=False)

   Rollno   Name  Marks
B     102  Priya     95
A     101   Arun     90
C     103  Rahul     83

In [3]:
import pandas as pd
data={
    'Rollno':[101,102,103],
    'Name':['Arun','Priya','Rahul'],
    'Marks':[85,90,78]
}
df=pd.DataFrame(data)
df.sort_values('Marks',
               ascending=True)

   Rollno   Name  Marks
2     103  Rahul     78
0     101   Arun     85
1     102  Priya     90

In [4]:
print(df[df['Marks']<90])

   Rollno   Name  Marks
0     101   Arun     85
2     103  Rahul     78

In [5]:
df.head()

   Rollno   Name  Marks
0     101   Arun     85
1     102  Priya     90
2     103  Rahul     78

In [7]:
data={
    'Rollno':[101,102,103,104,105,106,107,108,109,110],
    'Name':['Arun','Priya','Rahul','Denna','Bharath','Ram','Aarthi','Somesh','Vijay','Dhanush'],
    'Marks':[85,90,78,69,58,80,92,77,85,98]
}
df=pd.DataFrame(data)
df.tail()

   Rollno     Name  Marks
5     106      Ram     80
6     107   Aarthi     92
7     108   Somesh     77
8     109    Vijay     85
9     110  Dhanush     98

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rollno  10 non-null     int64
 1   Name    10 non-null     object
 2   Marks   10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [9]:
df.describe()

          Rollno      Marks
count   10.00000  10.000000
mean   105.50000  81.200000
std      3.02765  11.650465
min    101.00000  58.000000
25%    103.25000  77.250000
50%    105.50000  82.500000
75%    107.75000  88.750000
max    110.00000  98.000000

In [10]:
data={
    'Rollno':[101,102,103,104,105,106,107,108,109,110],
    'Name':['Arun','Priya','Rahul','Denna','Bharath','Ram','Aarthi','Somesh','Vijay','Dhanush'],
    'Dept':['Cs','Aids','Bcom','Bca','Ba','Ml','Ds','Mca','Msc','Be'],
    'Cgpa':[9,6,7,8,5,6,8,9,7,9]
}
df=pd.DataFrame(data)
print(df)

   Rollno     Name  Dept  Cgpa
0     101     Arun    Cs     9
1     102    Priya  Aids     6
2     103    Rahul  Bcom     7
3     104    Denna   Bca     8
4     105  Bharath    Ba     5
5     106      Ram    Ml     6
6     107   Aarthi    Ds     8
7     108   Somesh   Mca     9
8     109    Vijay   Msc     7
9     110  Dhanush    Be     9

In [13]:
data={
    'Rollno':[101,102,103,104,105,106,107,108,109,110],
    'Name':['Arun','Priya','Rahul','Denna','Bharath','Ram','Aarthi','Somesh','Vijay','Dhanush'],
    'Marks':[85,90,78,69,58,80,92,77,85,98]
}
df=pd.DataFrame(data)
print(df['Marks'].sum())
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].min())

812
81.2
98
58

In [17]:
data={
    'Name':['Arun','Priya','Rahul','Denna','Bharath','Ram','Aarthi'],
    'Salary':[85000,90000,38000,69000,58000,40000,92000]
}
df=pd.DataFrame(data)
print(df[df['Salary']>40000])

      Name  Salary
0     Arun   85000
1    Priya   90000
3    Denna   69000
4  Bharath   58000
6   Aarthi   92000

In [18]:
df.sort_values('Salary',
               ascending=True)

      Name  Salary
2    Rahul   38000
5      Ram   40000
4  Bharath   58000
3    Denna   69000
0     Arun   85000
1    Priya   90000
6   Aarthi   92000

In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Ibscai30.DGVC-MCA\Documents\students.csv.csv")
print(df)

   RollNo   Name Department  Marks
0     101   Arun        CSE     85
1     102  Priya         AI     92
2     103  Rahul         IT     78
3     104  Divya        CSE     88

In [3]:
print(df.size)

16

In [4]:
print(df.shape)

(4, 4)

In [5]:
print(df.describe)

<bound method NDFrame.describe of    RollNo   Name Department  Marks
0     101   Arun        CSE     85
1     102  Priya         AI     92
2     103  Rahul         IT     78
3     104  Divya        CSE     88>

In [6]:
df.head(2)

   RollNo   Name Department  Marks
0     101   Arun        CSE     85
1     102  Priya         AI     92

In [7]:
df.tail(3)

   RollNo   Name Department  Marks
1     102  Priya         AI     92
2     103  Rahul         IT     78
3     104  Divya        CSE     88

In [8]:
df.dtypes

RollNo         int64
Name          object
Department    object
Marks          int64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   RollNo      4 non-null      int64
 1   Name        4 non-null      object
 2   Department  4 non-null      object
 3   Marks       4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [11]:
print(df.loc[1])

RollNo          102
Name          Priya
Department       AI
Marks            92
Name: 1, dtype: object

In [12]:
print(df[df["Marks"]>80])

   RollNo   Name Department  Marks
0     101   Arun        CSE     85
1     102  Priya         AI     92
3     104  Divya        CSE     88

In [13]:
df["Grade"]=["A","A","B","A"]
print(df)

   RollNo   Name Department  Marks Grade
0     101   Arun        CSE     85     A
1     102  Priya         AI     92     A
2     103  Rahul         IT     78     B
3     104  Divya        CSE     88     A

In [14]:
df["Marks"]=df["Marks"]+5
print(df)

   RollNo   Name Department  Marks Grade
0     101   Arun        CSE     90     A
1     102  Priya         AI     97     A
2     103  Rahul         IT     83     B
3     104  Divya        CSE     93     A